### PR TITLE
Use of nil reference when connection cannot be opened.

### PR DESCRIPTION
**Pull request by kingbhanu**

### CODE REVIEW

**Comment by kingbhanu** [comment]
Yes, the connections ideally should not be closed in case of error. I am updating the PR.

**Comment by kingbhanu** [comment]
Also should I return any error if connection is found nil or just return error as nil?

**Comment by scott-wilson** [comment]
Hmm. Hard to say. I'm not sure if anything depends on that, so probably run the checks before you push an error if the conn is nil. Otherwise, I see no issue with it.

**Comment by collisonchris** [comment]
Calling close on a nil connection seems like it should throw an error back but it doesn't look like it is coded that way today. Go won't panic on a function call of a nil struct pointer so it'd be up to the programmer to handle these situations as desired. 

Though, I'm not sure what a caller would expect trying to call close on a nil connection object.

**Pull request merged**
